project:
  type: website
  output-dir: docs

website:
  title: "HDAT9700 Statistical Modelling II"
  description: "Term 3 2022"
  site-url: https://cbdrh-hdat9700.github.io/
  repo-url: https://github.com/CBDRH-HDAT9700/cbdrh-hdat9700.github.io
  repo-branch: master
  reader-mode: false
  search: true
  favicon: images/favicon.ico
  sidebar:
    tools:
      - icon: microsoft-teams
        url: https://google.com
    logo: images/Landscape__3.Mono_Pos_CBDRH.png
    pinned: true
    search: true
    style: "docked"
    collapse-level: 1
    contents:
      - text: Home
        href: index.qmd
      - section: Slides
        contents:
          - text: "Overview"
            href: slides-overview.qmd
          # - text: "Week 1. DAGs"
          #   href: slides-dags.qmd
          # - text: "Week 2. Matching"
          #   href: slides-psm.qmd
          # - text: "Week 3. MLM I"
          #   href: slides-mlm1.qmd
          # - text: "Week 4. MLM II"
          #   href: slides-mlm2.qmd
          # - text: "Week 5. MLM III"
          #   href: slides-mlm3.qmd
          # - text: "Week 7. Time series (pdf)"
          #   href: slides-tsa.pdf
          # - text: "Week 8. Interrupted time series (pdf)"
          #   href: slides-its.pdf
          # - text: "Week 9. Presenting and summarising model results (pdf)"
          #   href: slides-pres.pdf
          # - text: "Week 10. Missing data and multiple imputation (pdf)"
          #   href: slides-mi.pdf
      - text: Recordings
        href: recordings.qmd
      - text: Course outline
        href: course-outline.qmd
      - text: Contact
        href: contact.qmd
      - icon: microsoft-teams
        href: https://teams.microsoft.com/l/team/19%3a0qX2ugFhPmPHn9bW_gCcIp2nRbHdnYxP8Jb1Shy0JXk1%40thread.tacv2/conversations?groupId=d131ab27-83ee-4fcd-b419-bb485a17bba9&tenantId=3ff6cfa4-e715-48db-b8e1-0867b9f9fba3
      - icon: github
        href: https://github.com/CBDRH-HDAT9700/cbdrh-hdat9700.github.io
  page-footer:
    center:
      - text: "Â© UNSW 2023"

format:
  html:
    theme:
      light: [lumen, theme-hdat9700.scss]
      dark: [slate, theme-hdat9700-dark.scss]
    toc: true



