project:
  type: website
  output-dir: docs

website:
  title: "HDAT9700 Statistical Modelling II"
  description: "Term 3 2022"
  site-url: https://hdat9700.cbdrh.med.unsw.edu.au/
  repo-url: https://github.com/hds-teaching-cbdrh-med-unsw-edu-au/hdat9700
  repo-branch: master
  reader-mode: false
  search: true
  favicon: images/favicon.ico
  navbar:
    search: true
    logo: images/Landscape__4.Mono_Neg_CBDRH.png
    right:
      - text: Home
        href: index.qmd
      - text: Slides
        menu:
          - text: "Overview"
            href: slides-overview.qmd
          - text: "Week 1. DAGs"
            href: slides-dags.qmd
          # - text: "Week 2. Matching"
          #   href: slides-psm.qmd
          # - text: "Week 3. MLM I"
          #   href: slides-mlm1.qmd
          # - text: "Week 4. MLM II"
          #   href: slides-mlm2.qmd
          # - text: "Week 5. MLM III"
          #   href: slides-mlm3.qmd
          # - text: "Week 7. Time series (pdf)"
          #   href: slides-tsa.pdf
          # - text: "Week 8. Interrupted time series (pdf)"
          #   href: slides-its.pdf
          # - text: "Week 9. Presenting and summarising model results (pdf)"
          #   href: slides-pres.pdf
          # - text: "Week 10. Missing data and multiple imputation (pdf)"
          #   href: slides-mi.pdf
      - text: Recordings
        href: recordings.qmd
      - text: Course outline
        href: course-outline.qmd
      - text: Contact
        href: contact.qmd
      - icon: microsoft-teams
        href: https://teams.microsoft.com/l/channel/19%3a2nPUF6fRYGhZLb5NQTBjx9WaRv5qGh8FhE6wEPm0Vec1%40thread.tacv2/General?groupId=b21b1458-6e46-4eea-ace7-0cc8d76b6a94&tenantId=3ff6cfa4-e715-48db-b8e1-0867b9f9fba3
      - icon: github
        href: https://github.com/hds-teaching-cbdrh-med-unsw-edu-au/hdat9700
  page-footer:
    center:
      - text: "Â© UNSW 2023"

format:
  html:
    theme:
      light: [lumen, theme-hdat9700.scss]
      dark: [slate, theme-hdat9700-dark.scss]
    toc: true



